version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Unit Tests
          command: yarn test --coverage --ci --reporters=default --reporters=jest-junit
          when: always
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run:
          name: Send coverage
          command: yarn codecov
          when: always
      - run:
          name: Lint
          command: yarn lint --format junit -o reports/junit/js-lint-results.xml
          when: always
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - run:
          name: Build
          command: yarn build
          when: always
      - run:
          name: Check filesize
          command: yarn size
          when: always
