name: reports
on:
  workflow_run:
    workflows: ['main']
    types:
      - completed

jobs:
  report-unit-test:
    name: Unit Tests Report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      checks: write
    steps:
      - name: Publish Report
        uses: dorny/test-reporter@v2
        with:
          artifact: unit-test-results
          name: Unit Tests Report
          path: '*.xml'
          reporter: jest-junit
